# Problem Statement 2:
A dataset collected in a cosmetics shop showing details of customers and whether or not they responded to a special offer to buy a new lipstick is shown in the table below. Use this dataset to build a decision tree, with Buys as the target variable, to help in buying lip-sticks in the future. Find the root node of the decision tree. According to the decision tree, you have made from the previous Training data set, what is the decision for the test data: [Age < 21, Income = Low, Gender = Female, Marital Status = Married]? Write the concluding statement for the implemented application.


# Importing Libraries

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Making The Dict of the dataset

In [17]:
#Given Dataset
dataset = {
'Id':[1,2,3,4,5,6,7,8,9,10,11,12,13,14],
'Age':['<21','<21','21-35','>35','>35','>35','21-35','<21','<21','>35','<21','21-35','21-35','>35'],
'Income':['High','High','High','Medium','Low','Low','Low','Medium','Low','Medium','Medium','Medium','High','Medium'],
'Gender':['Male','Male','Male','Male','Female','Female','Female','Male','Female','Female','Female','Male','Female','Male'],
'MaritalStatus':['Single','Married','Single','Single','Single','Married','Married','Single','Married','Single','Married','Married','Single','Married'],
'Buys':['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']}

# Converting data to Dataframe

In [18]:
# here i convert dataset to dataframe
df = pd.DataFrame(dataset,columns=['Id','Age','Income','Gender','MaritalStatus','Buys'])

In [19]:
df

Id    Age  Income  Gender MaritalStatus Buys
0    1    <21    High    Male        Single   No
1    2    <21    High    Male       Married   No
2    3  21-35    High    Male        Single  Yes
3    4    >35  Medium    Male        Single  Yes
4    5    >35     Low  Female        Single  Yes
5    6    >35     Low  Female       Married   No
6    7  21-35     Low  Female       Married  Yes
7    8    <21  Medium    Male        Single   No
8    9    <21     Low  Female       Married  Yes
9   10    >35  Medium  Female        Single  Yes
10  11    <21  Medium  Female       Married  Yes
11  12  21-35  Medium    Male       Married  Yes
12  13  21-35    High  Female        Single  Yes
13  14    >35  Medium    Male       Married   No

In [20]:
df.shape


(14, 6)

# Checking The missing Values

In [42]:
df.isnull().sum()

Id               0
Age              0
Income           0
Gender           0
MaritalStatus    0
Buys             0
dtype: int64

# Preprocessing The Data by Lable Encoder

In [22]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
df['Age']= le.fit_transform(df['Age'])
df['Gender']= le.fit_transform(df['Gender'])
df['MaritalStatus']= le.fit_transform(df['MaritalStatus'])
df['Buys']= le.fit_transform(df['Buys'])
df['Income']= le.fit_transform(df['Income'])

# Getting Dependent and Independent Variables

In [23]:
x = df.iloc[:,1:-1].values

In [24]:
x

array([[1, 0, 1, 1],
       [1, 0, 1, 0],
       [0, 0, 1, 1],
       [2, 2, 1, 1],
       [2, 1, 0, 1],
       [2, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 2, 1, 1],
       [1, 1, 0, 0],
       [2, 2, 0, 1],
       [1, 2, 0, 0],
       [0, 2, 1, 0],
       [0, 0, 0, 1],
       [2, 2, 1, 0]])

In [25]:
y = df.iloc[:,-1].values

In [26]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

# # Building Training And Test Data to the train test

In [28]:
# Building Training And Test Data to the train test

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state=0)

In [29]:

x_train.shape,x_test.shape,y_train.shape,y_test.shape

((10, 4), (4, 4), (10,), (4,))

# #Model Building

In [34]:
#Model Building

from sklearn.tree import DecisionTreeClassifier
classfier =  DecisionTreeClassifier(criterion='entropy',random_state=0)
classfier.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

# Predicting The given data

In [35]:
# Prediction [<21=1, low=1, female=0,Married=0]

print(classfier.predict([[1,1,0,0]]))


[0]


In [37]:
y_pred = classfier.predict(x_test)
y_pred

array([0, 1, 0, 1])

# Calculating Confusion Matrix

In [38]:
# confusion Matrix

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cm = confusion_matrix(y_test,y_pred)

In [39]:
cm

array([[0, 0],
       [2, 2]], dtype=int64)

# Calculating Accuracy of the Model

In [40]:
accuracy_score(y_test,y_pred)

0.5

In [41]:
print((np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)))

[[0 1]
 [1 1]
 [0 1]
 [1 1]]


# Conclusion

# Here we are predicting the male/female will buys the lipstick or not. We are built the decision tree for that. It is the Probabilistic Algorithm. We convert all the catogorical data to the label form and then predict the values. Accuracy of model is 0.5 because the dataset is too short n model can't take decisions on that. But Decision tree predict the non-numeric value best if we want accuracy then we should go for random forest but if we want speed then the decision tree is the best model for building.